import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  bn: {
    shopName: 'ইউসুফ এন্টারপ্রাইজ',
    tagline: 'প্রিমিয়াম হুইল, লক এবং হ্যান্ডেল — পাইকারি সমাধান',
    location: 'ইউসুফ এন্টারপ্রাইজ — কারওয়ান বাজার, ঢাকা',
    importer: 'ডাইরেক্ট হোলসেল ইমপোর্টার',
    categories: 'প্রোডাক্ট ক্যাটাগরি সমূহ',
    navCategories: 'ক্যাটাগরি',
    viewProducts: 'পণ্য দেখুন →',
    home: 'হোম',
    allCategories: '← সব ক্যাটাগরি',
    price: 'মূল্য',
    perPiece: '/ পিস',
    perCarton: 'কার্টন / লট',
    selectSize: 'সাইজ নির্বাচন করুন:',
    wholesaleRate: 'পাইকারি দর:',
    quantity: 'পরিমাণ (পিস):',
    addToCart: 'কার্টে যোগ করুন',
    addedToCart: 'কার্টে যোগ করা হয়েছে',
    noProducts: 'এই ক্যাটাগরিতে এখনো কোনো প্রোডাক্ট যুক্ত করা হয়নি।',
    loading: 'লোড হচ্ছে...',
    login: 'লগইন',
    signup: 'রেজিস্টার',
    logout: 'লগআউট',
    orders: 'অর্ডার',
    account: 'অ্যাকাউন্ট',
    cart: 'কার্ট',
    search: 'পণ্য খুঁজুন',
    searchPlaceholder: 'হুইল, লক, হ্যান্ডেল...',
    searchEmpty: 'এই নামে কোনো পণ্য পাওয়া যায়নি।',
    searchHint: 'পণ্যের নাম লিখে খুঁজুন।',
    inStock: 'স্টকে আছে',
    outOfStock: 'স্টক আউট',
    wholesaleExclusive: 'হোলসেল এক্সক্লুসিভ',
    switchToEn: 'English',
    switchToBn: 'বাংলা',
    cartTitle: 'পাইকারি অর্ডার কার্ট',
    cartEmpty: 'কার্টটি খালি রয়েছে',
    cartEmptyBody: 'ক্যাটাগরি থেকে পণ্য যোগ করলে এখানে দেখাবে।',
    shopNameField: 'দোকানের নাম / মার্কেট',
    yourName: 'আপনার নাম',
    phoneRequired: 'মোবাইল নম্বর (আবশ্যক)*',
    address: 'ঠিকানা / জেলা',
    paymentMethod: 'পেমেন্ট পদ্ধতি',
    cod: 'ক্যাশ অন ডেলিভারি',
    bkash: 'বিকাশ',
    nagad: 'নগদ',
    bank: 'ব্যাংক ট্রান্সফার',
    trxId: 'ট্রানজেকশন আইডি (TrxID)',
    trxPlaceholder: 'যেমন: 8A5K2L9P',
    receiptRef: 'রসিদ রেফারেন্স (ঐচ্ছিক)',
    receiptPlaceholder: 'SMS বা স্লিপ নম্বর',
    total: 'মোট বিল',
    confirmOrder: 'অর্ডার কনফার্ম করুন',
    submitting: 'অর্ডার জমা হচ্ছে...',
    clearCart: 'কার্ট খালি করুন',
    orderSuccess: 'অর্ডার গ্রহণ করা হয়েছে',
    orderSuccessBody: 'ধন্যবাদ! ইউসুফ এন্টারপ্রাইজ খুব শীঘ্রই আপনার মোবাইলে কল দিয়ে অর্ডার কনফার্ম করবে।',
    tracking: 'ট্র্যাকিং নম্বর',
    gotIt: 'ঠিক আছে',
    phoneMissing: 'অনুগ্রহ করে মোবাইল নম্বরটি লিখুন।',
    trxMissing: 'বিকাশ বা ব্যাংক পেমেন্টের TrxID লিখুন।',
    orderError: 'অর্ডার প্রক্রিয়ায় সমস্যা হয়েছে।',
    checkout: 'চেকআউট',
    viewCart: 'কার্ট দেখুন',
    pcs: 'পিস',
    minLot: 'ন্যূনতম লট',
    ordersTitle: 'অর্ডার ইতিহাস',
    ordersEmpty: 'এখনো কোনো অর্ডার নেই',
    ordersEmptyBody: 'লগইন করে রাখা অর্ডার এখানে দেখা যাবে। অর্ডার দিলেও ফোন নম্বর দিয়ে খুঁজে দেখতে পারবেন।',
    ordersGuest: 'অর্ডার দেখতে লগইন করুন, অথবা যে নম্বরে অর্ডার দিয়েছেন সেটি লিখুন।',
    findOrders: 'অর্ডার খুঁজুন',
    noMatchOrders: 'এই নম্বরে কোনো অর্ডার পাওয়া যায়নি।',
    categoryMissing: 'ক্যাটাগরি খুঁজে পাওয়া যায়নি',
    copy: 'কপি',
    copied: 'কপি হয়েছে',
    copyFailed: 'কপি করা যায়নি',
    paymentPending: 'অপেক্ষমাণ',
    paymentVerified: 'পেইড / ভেরিফাইড',
    paymentFailed: 'ব্যর্থ',
    sendMoney: 'Send Money করুন, তারপর TrxID দিন।',
    bkashSendTo: 'বিকাশ পার্সোনাল নম্বর',
    bankHint: 'ট্রান্সফারের আগে এই নম্বরে কল করে অ্যাকাউন্ট নম্বর নিশ্চিত করুন।',
    accountName: 'অ্যাকাউন্টের নাম',
    reference: 'রেফারেন্স',
    close: 'বন্ধ',
    browse: 'ক্যাটাগরি দেখুন',
    email: 'ইমেইল',
    password: 'পাসওয়ার্ড',
    checkingAuth: 'লগইন সিকিউরিটি যাচাই করা হচ্ছে...',
  },
  en: {
    shopName: 'Yousuf Enterprise',
    tagline: 'Premium Wheels, Locks & Handles — Wholesale Solutions',
    location: 'Yousuf Enterprise — Karwan Bazar, Dhaka',
    importer: 'Direct Wholesale Importer',
    categories: 'Product Categories',
    navCategories: 'Categories',
    viewProducts: 'View Products →',
    home: 'Home',
    allCategories: '← All Categories',
    price: 'Price',
    perPiece: '/ pc',
    perCarton: 'Carton / lot',
    selectSize: 'Select Size:',
    wholesaleRate: 'Wholesale Rate:',
    quantity: 'Quantity (pcs):',
    addToCart: 'Add to Cart',
    addedToCart: 'Item added to cart',
    noProducts: 'No products added to this category yet.',
    loading: 'Loading...',
    login: 'Login',
    signup: 'Sign Up',
    logout: 'Logout',
    orders: 'Orders',
    account: 'Account',
    cart: 'Cart',
    search: 'Search products',
    searchPlaceholder: 'Wheels, locks, handles...',
    searchEmpty: 'No products match that search.',
    searchHint: 'Type a product name to search.',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    wholesaleExclusive: 'Wholesale Exclusive',
    switchToEn: 'English',
    switchToBn: 'বাংলা',
    cartTitle: 'Wholesale Cart',
    cartEmpty: 'Your cart is empty',
    cartEmptyBody: 'Add products from a category and they will show up here.',
    shopNameField: 'Shop / Market Name',
    yourName: 'Your Name',
    phoneRequired: 'Mobile Number (Required)*',
    address: 'Delivery Address / District',
    paymentMethod: 'Payment Method',
    cod: 'Cash on Delivery',
    bkash: 'bKash',
    nagad: 'Nagad',
    bank: 'Bank Transfer',
    trxId: 'Transaction ID (TrxID)',
    trxPlaceholder: 'e.g. 8A5K2L9P',
    receiptRef: 'Receipt reference (optional)',
    receiptPlaceholder: 'SMS or slip number',
    total: 'Total',
    confirmOrder: 'Confirm Wholesale Order',
    submitting: 'Submitting...',
    clearCart: 'Clear Cart',
    orderSuccess: 'Order placed successfully',
    orderSuccessBody: 'Thank you. Yousuf Enterprise will call your mobile shortly to confirm the order.',
    tracking: 'Tracking number',
    gotIt: 'Got it',
    phoneMissing: 'Please enter your mobile number.',
    trxMissing: 'Enter the bKash or bank Transaction ID.',
    orderError: 'Something went wrong while placing the order.',
    checkout: 'Checkout',
    viewCart: 'View cart',
    pcs: 'pcs',
    minLot: 'Minimum lot',
    ordersTitle: 'Order History',
    ordersEmpty: 'No orders yet',
    ordersEmptyBody: 'Orders placed on your account will appear here. You can also look up a number used at checkout.',
    ordersGuest: 'Log in to see your orders, or search with the mobile number used at checkout.',
    findOrders: 'Find orders',
    noMatchOrders: 'No orders found for this number.',
    categoryMissing: 'Category not found',
    copy: 'Copy',
    copied: 'Copied',
    copyFailed: 'Could not copy',
    paymentPending: 'Pending',
    paymentVerified: 'Paid / Verified',
    paymentFailed: 'Failed',
    sendMoney: 'Send money, then enter the TrxID.',
    bkashSendTo: 'bKash personal number',
    bankHint: 'Call this number to confirm the account before you transfer.',
    accountName: 'Account name',
    reference: 'Reference',
    close: 'Close',
    browse: 'Browse categories',
    email: 'Email',
    password: 'Password',
    checkingAuth: 'Checking login security...',
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => localStorage.getItem('app_lang') || 'bn');

  const setLang = (nextLang) => {
    const value = nextLang === 'en' ? 'en' : 'bn';
    setLangState(value);
    localStorage.setItem('app_lang', value);
  };

  const toggleLanguage = () => setLang(lang === 'bn' ? 'en' : 'bn');

  const t = translations[lang] || translations.bn;

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
