import { createContext, useContext, useEffect, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  bn: {
    shopName: 'ইউসুফ এন্টারপ্রাইজ',
    tagline: 'প্রিমিয়াম হুইল, তালা ও হ্যান্ডেল — পাইকারি সরবরাহ',
    location: 'ইউসুফ এন্টারপ্রাইজ — কারওয়ান বাজার, ঢাকা',
    importer: 'সরাসরি আমদানিকারক',
    categories: 'ক্যাটাগরি সমূহ',
    navCategories: 'ক্যাটাগরি',
    viewProducts: 'পণ্য দেখুন',
    home: 'হোম',
    allCategories: 'সব ক্যাটাগরি',
    back: 'ব্যাক',
    price: 'মূল্য',
    perPiece: '/ পিস',
    perCarton: 'কার্টন / লট',
    selectSize: 'সাইজ বাছুন',
    wholesaleRate: 'পাইকারি রেট',
    quantity: 'পরিমাণ (পিস)',
    addToCart: 'কার্টে যোগ করুন',
    addedToCart: 'কার্টে যোগ হয়েছে',
    addedBody: 'পণ্যটি কার্টে যোগ হয়েছে। কেনাকাটা চালিয়ে যান, অথবা এখনই অর্ডার করুন।',
    noProducts: 'এই ক্যাটাগরিতে এখনো কোনো পণ্য যোগ করা হয়নি।',
    loading: 'লোড হচ্ছে...',
    login: 'প্রবেশ',
    signup: 'নিবন্ধন',
    logout: 'প্রস্থান',
    orders: 'অর্ডার',
    account: 'অ্যাকাউন্ট',
    cart: 'কার্ট',
    search: 'পণ্য খুঁজুন',
    searchPlaceholder: 'হুইল, তালা, হ্যান্ডেল...',
    searchEmpty: 'এই নামে কোনো পণ্য পাওয়া যায়নি।',
    searchHint: 'পণ্যের নাম লিখে খুঁজুন।',
    inStock: 'স্টকে আছে',
    outOfStock: 'স্টক নেই',
    wholesaleExclusive: 'শুধু পাইকারি',
    switchToEn: 'English',
    switchToBn: 'বাংলা',
    cartTitle: 'পাইকারি কার্ট',
    cartEmpty: 'কার্ট এখন খালি',
    cartEmptyBody: 'ক্যাটাগরি থেকে পণ্য যোগ করলে এখানে দেখা যাবে।',
    shopNameField: 'দোকানের নাম / মার্কেট',
    yourName: 'আপনার নাম',
    phoneRequired: 'মোবাইল নম্বর (আবশ্যক)',
    address: 'ঠিকানা / জেলা',
    paymentMethod: 'পেমেন্ট পদ্ধতি',
    cod: 'হাতে পেয়ে পরিশোধ',
    bkash: 'বিকাশ',
    nagad: 'নগদ',
    bank: 'ব্যাংক স্থানান্তর',
    trxId: 'লেনদেন নম্বর',
    trxPlaceholder: 'যেমন: 8A5K2L9P',
    receiptRef: 'রসিদ নম্বর (ঐচ্ছিক)',
    receiptPlaceholder: 'বার্তা বা স্লিপ নম্বর',
    senderNumber: 'প্রেরকের নম্বর',
    senderPlaceholder: 'যে নম্বর থেকে টাকা পাঠানো হয়েছে',
    senderMissing: 'প্রেরকের মোবাইল নম্বর লিখুন।',
    total: 'মোট বিল',
    lineSubtotal: 'এই পণ্যের মোট',
    confirmOrder: 'অর্ডার নিশ্চিত করুন',
    submitting: 'অর্ডার জমা হচ্ছে...',
    clearCart: 'কার্ট খালি করুন',
    orderSuccess: 'অর্ডার গ্রহণ করা হয়েছে',
    orderSuccessBody: 'ধন্যবাদ। ইউসুফ এন্টারপ্রাইজ শীঘ্রই আপনার মোবাইলে কল করে অর্ডার নিশ্চিত করবে।',
    tracking: 'ট্র্যাকিং নম্বর',
    gotIt: 'ঠিক আছে',
    phoneMissing: 'অনুগ্রহ করে মোবাইল নম্বর লিখুন।',
    trxMissing: 'বিকাশ বা ব্যাংক পেমেন্টের লেনদেন নম্বর লিখুন।',
    orderError: 'অর্ডার প্রক্রিয়ায় সমস্যা হয়েছে। আবার চেষ্টা করুন।',
    checkout: 'চেকআউট',
    checkoutTitle: 'অর্ডার সম্পন্ন করুন',
    viewCart: 'কার্ট দেখুন',
    continueShopping: 'আরো প্রোডাক্ট দেখুন',
    proceedCheckout: 'সরাসরি অর্ডার করুন',
    pcs: 'পিস',
    minLot: 'ন্যূনতম লট',
    ordersTitle: 'অর্ডার ইতিহাস',
    ordersEmpty: 'এখনো কোনো অর্ডার নেই',
    ordersEmptyBody: 'লগইন করে রাখা অর্ডার এখানে দেখা যাবে। অর্ডার দিলেও ফোন নম্বর দিয়ে খুঁজে দেখতে পারবেন।',
    ordersGuest: 'অর্ডার দেখতে প্রবেশ করুন, অথবা যে নম্বরে অর্ডার দিয়েছেন সেটি লিখুন।',
    findOrders: 'অর্ডার খুঁজুন',
    noMatchOrders: 'এই নম্বরে কোনো অর্ডার পাওয়া যায়নি।',
    categoryMissing: 'ক্যাটাগরি খুঁজে পাওয়া যায়নি',
    copy: 'কপি',
    copied: 'কপি হয়েছে',
    copyFailed: 'কপি করা যায়নি',
    paymentPending: 'অপেক্ষমাণ',
    paymentVerified: 'পরিশোধিত',
    paymentFailed: 'ব্যর্থ',
    sendMoney: 'টাকা পাঠান, তারপর লেনদেন নম্বর ও প্রেরকের নম্বর লিখুন।',
    bkashSendTo: 'বিকাশ নম্বর',
    bankHint: 'টাকা পাঠানোর আগে এই নম্বরে কল করে হিসাব নিশ্চিত করুন।',
    accountName: 'হিসাবের নাম',
    reference: 'রেফারেন্স',
    close: 'বন্ধ',
    browse: 'ক্যাটাগরি দেখুন',
    email: 'ইমেইল',
    password: 'পাসওয়ার্ড',
    checkingAuth: 'প্রবেশ নিরাপত্তা যাচাই হচ্ছে...',
    call: 'কল',
    whatsapp: 'হোয়াটসঅ্যাপ',
    help: 'সহায়তা',
    productsWord: 'টি পণ্য',
    details: 'বিস্তারিত',
    decrease: 'কমান',
    increase: 'বাড়ান',
    remove: 'সরান',
    contactSection: 'যোগাযোগ ও ঠিকানা',
    reviewSection: 'আপনার পণ্য',
    codHint: 'পণ্য হাতে পেয়ে টাকা দিবেন।',
    personal: 'ব্যক্তিগত',
    branch: 'শাখা',
    googleContinue: 'গুগল দিয়ে প্রবেশ',
    checkEmail: 'ইমেইল দেখুন',
    confirmEmailSent: 'নিশ্চিতকরণ ইমেইল পাঠানো হয়েছে',
    haveAccount: 'আগে থেকে অ্যাকাউন্ট আছে? প্রবেশ করুন',
    noAccount: 'নতুন অ্যাকাউন্ট খুলুন',
    authFailed: 'প্রবেশ করা যায়নি। তথ্য যাচাই করে আবার চেষ্টা করুন।',
    badLogin: 'ইমেইল বা পাসওয়ার্ড সঠিক নয়।',
    support: 'সহায়তা',
    trustRate: 'পাইকারি রেট',
    trustStock: 'স্টকে আছে',
    yourOrder: 'আপনার অর্ডার',
  },
  en: {
    shopName: 'Yousuf Enterprise',
    tagline: 'Premium wheels, locks and handles — wholesale supply',
    location: 'Yousuf Enterprise — Karwan Bazar, Dhaka',
    importer: 'Direct importer',
    categories: 'Categories',
    navCategories: 'Categories',
    viewProducts: 'View products',
    home: 'Home',
    allCategories: 'All categories',
    back: 'Back',
    price: 'Price',
    perPiece: '/ pc',
    perCarton: 'Carton / lot',
    selectSize: 'Select size',
    wholesaleRate: 'Wholesale rate',
    quantity: 'Quantity (pcs)',
    addToCart: 'Add to cart',
    addedToCart: 'Added to cart',
    addedBody: 'This item is in your cart. Keep browsing, or place the order now.',
    noProducts: 'No products have been added to this category yet.',
    loading: 'Loading...',
    login: 'Log in',
    signup: 'Register',
    logout: 'Log out',
    orders: 'Orders',
    account: 'Account',
    cart: 'Cart',
    search: 'Search products',
    searchPlaceholder: 'Wheels, locks, handles...',
    searchEmpty: 'No products match that search.',
    searchHint: 'Type a product name to search.',
    inStock: 'In stock',
    outOfStock: 'Out of stock',
    wholesaleExclusive: 'Wholesale only',
    switchToEn: 'English',
    switchToBn: 'বাংলা',
    cartTitle: 'Wholesale cart',
    cartEmpty: 'Your cart is empty',
    cartEmptyBody: 'Add products from a category and they will show up here.',
    shopNameField: 'Shop / market name',
    yourName: 'Your name',
    phoneRequired: 'Mobile number (required)',
    address: 'Address / district',
    paymentMethod: 'Payment method',
    cod: 'Cash on delivery',
    bkash: 'bKash',
    nagad: 'Nagad',
    bank: 'Bank transfer',
    trxId: 'Transaction ID',
    trxPlaceholder: 'e.g. 8A5K2L9P',
    receiptRef: 'Receipt reference (optional)',
    receiptPlaceholder: 'Message or slip number',
    senderNumber: 'Sender number',
    senderPlaceholder: 'Number the payment was sent from',
    senderMissing: 'Enter the sender mobile number.',
    total: 'Total',
    lineSubtotal: 'Line total',
    confirmOrder: 'Confirm order',
    submitting: 'Submitting order...',
    clearCart: 'Clear cart',
    orderSuccess: 'Order received',
    orderSuccessBody: 'Thank you. Yousuf Enterprise will call your mobile shortly to confirm the order.',
    tracking: 'Tracking number',
    gotIt: 'Done',
    phoneMissing: 'Please enter your mobile number.',
    trxMissing: 'Enter the bKash or bank transaction ID.',
    orderError: 'The order could not be placed. Please try again.',
    checkout: 'Checkout',
    checkoutTitle: 'Complete your order',
    viewCart: 'View cart',
    continueShopping: 'Continue shopping',
    proceedCheckout: 'Proceed to checkout',
    pcs: 'pcs',
    minLot: 'Minimum lot',
    ordersTitle: 'Order history',
    ordersEmpty: 'No orders yet',
    ordersEmptyBody: 'Orders on your account appear here. You can also look up the mobile number used at checkout.',
    ordersGuest: 'Log in to see your orders, or search with the mobile number used at checkout.',
    findOrders: 'Find orders',
    noMatchOrders: 'No orders found for this number.',
    categoryMissing: 'Category not found',
    copy: 'Copy',
    copied: 'Copied',
    copyFailed: 'Could not copy',
    paymentPending: 'Pending',
    paymentVerified: 'Paid',
    paymentFailed: 'Failed',
    sendMoney: 'Send the money, then enter the transaction ID and sender number.',
    bkashSendTo: 'bKash number',
    bankHint: 'Call this number to confirm the account before you transfer.',
    accountName: 'Account name',
    reference: 'Reference',
    close: 'Close',
    browse: 'Browse categories',
    email: 'Email',
    password: 'Password',
    checkingAuth: 'Checking login security...',
    call: 'Call',
    whatsapp: 'WhatsApp',
    help: 'Help',
    productsWord: 'items',
    details: 'Details',
    decrease: 'Decrease',
    increase: 'Increase',
    remove: 'Remove',
    contactSection: 'Contact and address',
    reviewSection: 'Your items',
    codHint: 'Pay when the goods arrive.',
    personal: 'Personal',
    branch: 'Branch',
    googleContinue: 'Continue with Google',
    checkEmail: 'Check your email',
    confirmEmailSent: 'A confirmation email has been sent',
    haveAccount: 'Already have an account? Log in',
    noAccount: 'Create an account',
    authFailed: 'Could not sign in. Check your details and try again.',
    badLogin: 'Email or password is incorrect.',
    support: 'Support',
    trustRate: 'Wholesale rate',
    trustStock: 'In stock',
    yourOrder: 'Your order',
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => localStorage.getItem('app_lang') || 'bn');

  const setLang = (nextLang) => {
    const value = nextLang === 'en' ? 'en' : 'bn';
    setLangState(value);
    localStorage.setItem('app_lang', value);
  };

  const toggleLanguage = () => setLang(lang === 'bn' ? 'en' : 'bn');

  useEffect(() => {
    document.documentElement.lang = lang === 'bn' ? 'bn' : 'en';
  }, [lang]);

  const t = translations[lang] || translations.bn;

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
